name: flutterr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  firebase_core: ^2.15.0
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/7.png
    - assets/images/8.png
    - assets/images/9.png
    - assets/images/10.png
    - assets/images/11.png
    - assets/images/12.png
    - assets/images/apple.png 
    - assets/images/ball.png
    - assets/images/books.png
    - assets/images/car.png
    - assets/images/cat.png
    - assets/images/chair.png
    - assets/images/dog.png
    - assets/images/house.png
    - assets/images/tree.png
    - assets/images/shoes.png
    - assets/images/water.png
    - assets/images/sun.png
    - assets/images/brazil.png
    - assets/images/canada.png
    - assets/images/china.png
    - assets/images/france.png
    - assets/images/germany.png
    - assets/images/india.png
    - assets/images/italy.png
    - assets/images/japan.png
    - assets/images/philippines.png
    - assets/images/south_korea.png
    - assets/images/united_kingdom.png
    - assets/images/usa.png

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P.ttf
